name: app_profesor
description: "Profeshor 1.0"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Estado y arquitectura
  flutter_riverpod: ^2.0.2

  # Base de datos local
  sqflite: ^2.3.0
  path: ^1.9.0
  path_provider: ^2.0.15

  # Persistencia y configuraci贸n
  shared_preferences: ^2.2.0
  flutter_dotenv: ^5.2.1

  # Utilidades
  logger: ^2.0.2
  intl: ^0.20.2
  collection: ^1.18.0

  # Supabase (backend opcional)
  supabase_flutter: ^2.0.0

  # Importaci贸n y exportaci贸n de archivos
  excel: ^2.0.6
  file_selector: ^1.0.3

  # Permisos (para Android/iOS)
  permission_handler: ^11.0.1

  # Iconos y animaciones
  cupertino_icons: ^1.0.8
  lottie: ^2.7.0

  # Navegaci贸n y enlaces
  url_launcher: ^6.2.1

  share_plus: ^7.2.1

  # Localizaci贸n
  flutter_localizations:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/animations/loading.json
    - assets/animations/success.json
    - assets/animations/error.json

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1 #  nuevo

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/logo.png" #  usa tu logo actual o reemplaza por uno cuadrado